-- Migration: add additional fields to users table
-- Run this after initial schema creation
ALTER TABLE `users`
    ADD COLUMN `username` VARCHAR(150) NULL AFTER `email`,
    ADD COLUMN `password_hash` VARCHAR(255) NULL AFTER `username`,
    ADD COLUMN `phone` VARCHAR(20) NULL AFTER `password_hash`,
    ADD COLUMN `alternate_phone` VARCHAR(20) NULL AFTER `phone`,
    ADD COLUMN `dob` DATE NULL AFTER `alternate_phone`,
    ADD COLUMN `gender` ENUM('Male','Female','Other') NULL AFTER `dob`,
    ADD COLUMN `address` VARCHAR(255) NULL AFTER `gender`,
    ADD COLUMN `city` VARCHAR(100) NULL AFTER `address`,
    ADD COLUMN `state` VARCHAR(100) NULL AFTER `city`,
    ADD COLUMN `country` VARCHAR(100) NULL AFTER `state`,
    ADD COLUMN `pincode` VARCHAR(20) NULL AFTER `country`,
    ADD COLUMN `bio` TEXT NULL AFTER `pincode`,
    ADD COLUMN `profile_image` VARCHAR(255) NULL AFTER `bio`,
    ADD COLUMN `cover_image` VARCHAR(255) NULL AFTER `profile_image`,
    ADD COLUMN `occupation` VARCHAR(150) NULL AFTER `cover_image`,
    ADD COLUMN `is_student` TINYINT(1) DEFAULT 0 AFTER `occupation`,
    ADD COLUMN `college_name` VARCHAR(150) NULL AFTER `is_student`,
    ADD COLUMN `college_registration_number` VARCHAR(50) NULL AFTER `college_name`,
    ADD COLUMN `roll_number` VARCHAR(50) NULL AFTER `college_registration_number`,
    ADD COLUMN `branch` VARCHAR(100) NULL AFTER `roll_number`,
    ADD COLUMN `year_of_study` VARCHAR(20) NULL AFTER `branch`,
    ADD COLUMN `graduation_year` YEAR NULL AFTER `year_of_study`,
    ADD COLUMN `linkedin_url` VARCHAR(255) NULL AFTER `graduation_year`,
    ADD COLUMN `github_url` VARCHAR(255) NULL AFTER `linkedin_url`,
    ADD COLUMN `portfolio_url` VARCHAR(255) NULL AFTER `github_url`,
    ADD COLUMN `skills` TEXT NULL AFTER `portfolio_url`,
    ADD COLUMN `emergency_contact_name` VARCHAR(150) NULL AFTER `skills`,
    ADD COLUMN `emergency_contact_phone` VARCHAR(20) NULL AFTER `emergency_contact_name`,
    ADD COLUMN `last_profile_updated_at` TIMESTAMP NULL AFTER `emergency_contact_phone`;
